ribbon:
  eureka:
    enabled: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enable: true
      trace:
        enable: true
  zipkin：
    base-url:http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

version: v5