spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: hello
          uri: lb://CLIENT
          predicates:
          - Path=/hello/**
    bus:
      enable: true
      trace:
        enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin：
    base-url:http://localhost:9411

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
    cors:
        allowed-origins: "*"
        allowed-methods: "*"

version: v5