spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: hello
          uri: lb://CLIENT
          predicates:
          - Path=/hello/**