spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enable: true
      trace:
        enable: true
  
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  app-config: service-hello,client
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  instanceUrlSuffix: hystrix.stream
