spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enable: true
      trace:
        enable: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh